version: '3.7'
services:
# Reverse proxy wit acme TLS support
  traefik:
    container_name: $STACK-traefik
    image: traefik:v1.7.16
    ports:
      - "80:80" # The HTTP port
      - "443:443" # The HTTPS port
    expose:
      - 8080
    command: --api # Enables the web UI
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$TRAEFIK.$DOMAIN" # Domain name for the app
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=1"
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik.toml:/traefik.toml # Traefik configuration file
      - traefik_acme:/acme # Tell Traefik to save SSL certs here
    networks:
      - mediacenter

volumes:
  traefik_acme:

networks:
  mediacenter:
    name: docker-traefik-proxy_net
  ldap:
    name: ldap_net
    # internal: false