version: '2.4'
services:
# Reverse proxy wit acme TLS support
  traefik:
    container_name: $STACK-web
    image: traefik:v2.1
    ports:
      # - "80:80" # The HTTP port
      - "443:443" # The HTTPS port
      # - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$STACK-traefik.rule=Host(`$TRAEFIK.$DOMAIN`)"
      - "traefik.http.routers.$STACK-traefik.service=api@internal"
      - "traefik.http.routers.$STACK-traefik.entrypoints=websecure"
      - "traefik.http.routers.$STACK-traefik.tls.certresolver=mytlschallenge"
      - "traefik.http.services.$STACK-traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.$STACK-traefik.middlewares=auth-admin"
      - "traefik.http.middlewares.auth-admin.forwardauth.address=http://mediacenter-organizr/api/?v1/auth&group=1"
      - "com.centurylinklabs.watchtower.enable=true"
    command:
      - "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=$ACME_EMAIL"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    volumes:
      - traefik_letsencrypt:/letsencrypt # Tell Traefik to save SSL certs here
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
    networks:
      - net

# Watchtower auto update
  watchtower:
    image: "v2tec/watchtower"
    container_name: $STACK-watchtower
    restart: always
    command:
      - --label-enable
      - --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

# DDclient cloudflare dns auto updater
  ddclient:
    image: "linuxserver/ddclient"
    container_name: $STACK-ddclient
    restart: always
    environment:
      - TZ=$TIMEZONE
      - PGID=$PGID
      - PUID=$PUID
    volumes:
      - ddclient_config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

volumes:
  traefik_letsencrypt:
      name: $STACK-letsencrypt # Real ending name
      external: false
  ddclient_config:
      name: $STACK-ddclient_config # Real ending name
      external: false

networks:
  net:
    name: traefik-proxy_net
