version: '3.7'
services:
# Reverse proxy wit acme TLS support
  traefik:
    container_name: $STACK-web
    image: traefik:v2.1
    ports:
      - "80:80" # The HTTP port
      # - "443:443" # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    command:
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure # Don't do that in production
      --certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=$ACME_EMAIL
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    volumes:
      - $APPDATA/$STACK/acme:/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
    networks:
      - net

networks:
  net:
    name: traefik-proxy_net
