version: '3.7'
services:
# Reverse proxy wit acme TLS support
  traefik:
    container_name: $STACK-web
    image: traefik:v2.1
    ports:
      - "80:80" # The HTTP port
      # - "443:443" # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure # Don't do that in production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`$TRAEFIK.$DOMAIN`)"
      - "traefik.http.routers.traefik.entrypoints=web"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
    networks:
      - net

networks:
  net:
    name: traefik-proxy_net
