version: '3.4'
services:
# Reverse proxy & Front end
  traefik:
    container_name: $STACK-$TRAEFIK
    image: traefik
    command: --api # Enables the web UI
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:$TRAEFIK.$DOMAIN" # Domain name for the app
      - "traefik.port=8080"
    ports:
      - "80:80" # The HTTP port
      - "443:443" # The HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - traefik.toml:/traefik.toml # Traefik configuration file
      - $APPDATA/$STACK/$TRAEFIK/traefik-acme:/acme # Tell Traefik to save SSL certs here
    networks:
      - int_net

networks:
  int_net:
    internal: false
      name: $STACK_net