version: '2.4'
services:
# Reverse proxy wit acme TLS support
  traefik:
    container_name: $STACK-web
    image: traefik:v2.1
    ports:
      # - "80:80" # The HTTP port
      - "443:443" # The HTTPS port
      # - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$STACK-traefik.rule=Host(`$TRAEFIK.$DOMAIN`)"
      - "traefik.http.routers.$STACK-traefik.service=api@internal"
      - "traefik.http.routers.$STACK-traefik.entrypoints=websecure"
      - "traefik.http.routers.$STACK-traefik.tls.certresolver=mytlschallenge"
      - "traefik.http.services.$STACK-traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.$STACK-traefik.middlewares=auth-admin"
      - "traefik.http.middlewares.auth-admin.forwardauth.address=http://mediacenter-organizr/api/?v1/auth&group=1"
    command:
      - "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=$ACME_EMAIL"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    volumes:
      - traefik:/letsencrypt # Tell Traefik to save SSL certs here
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
    networks:
      - net

  bivac:
    container_name: $STACK-backup
    image: camptocamp/bivac:stable
    # ports:
    #   - "8182:8182"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$STACK-bivac.rule=Host(`$BIVAC.$DOMAIN`)"
      - "traefik.http.routers.$STACK-bivac.service=api@internal"
      - "traefik.http.routers.$STACK-bivac.entrypoints=websecure"
      - "traefik.http.routers.$STACK-bivac.tls.certresolver=mytlschallenge"
      - "traefik.http.services.$STACK-bivac.loadbalancer.server.port=8182"
      - "traefik.http.routers.$STACK-bivac.middlewares=auth-admin"
      - "traefik.http.middlewares.auth-admin.forwardauth.address=http://mediacenter-organizr/api/?v1/auth&group=1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $APPDATA/backup:/data/backup
    networks:
      - net

volumes:
  traefik:
      name: $STACK-letsencrypt # Real ending name
      external: false

networks:
  net:
    name: traefik-proxy_net
